for alf = 0:0.01:2
    ip = [alf * (alf - 1) * (alf - 2) / -6, ...
                (alf - 1) * (alf + 1) * (alf - 2) / 2, ...
                alf * (alf + 1) * (alf - 2) / -2, ...
                alf * (alf + 1) * (alf - 1) / 6];
    customIp = [alf * (alf + 1) / -((alf + 2) * (alf + 3)); ...
                        2 * alf * (alf + 1) / ((alf + 1) * (alf + 2)); ...
                        2 * (alf + 1) / ((alf + 2) * (alf + 1)); ...
                        2 * alf / -((alf + 3) * (alf + 2))];
    plot(customIp)
    ylim([-1, 1])
    drawnow;
end