matSave = [];
for alf = 0:0.01:10
    ip = [alf * (alf - 1) * (alf - 2) / -6, ...
                (alf - 1) * (alf + 1) * (alf - 2) / 2, ...
                alf * (alf + 1) * (alf - 2) / -2, ...
                alf * (alf + 1) * (alf - 1) / 6];
    customIp = [alf * (alf + 1) / -((alf + 2) * (alf + 3)); ...
                        2 * alf * (alf + 1) / ((alf + 1) * (alf + 2)); ...
                        2 * (alf + 1) / ((alf + 2) * (alf + 1)); ...
                        2 * alf / -((alf + 3) * (alf + 2))];
    matSave = [matSave; inv([1, -ip(4); -ip(4), 1])];
%     hold off;
%     plot(customIp)
%     hold on;
%     plot(ip)
%     ylim([-1, 1])
    drawnow;
end